import { getErrorMessage, toError } from '@lichens-innovation/ts-common';
import { readFileSync, writeFileSync } from 'node:fs';
import { createLogger } from 'vite';

const logger = createLogger();

const packageJsonPath = './package.json';
const versionGenFilename = './src/constants.ts';

type PackageJsonData = {
  name: string;
  description: string;
  version: string;
  author: string;
  repository: unknown;
  [key: string]: unknown;
};

const readPackageJson = (): PackageJsonData => {
  const content = readFileSync(packageJsonPath, { encoding: 'utf8' });
  return JSON.parse(content) as PackageJsonData;
};

const generateConstantsFile = (
  packageMetadata: PackageJsonData,
  version: string,
): string => {
  const { name, description, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split('T')[0];

  return `// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.ts
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: ${JSON.stringify(name)},
  DESCRIPTION: ${JSON.stringify(description)},
  REPOSITORY: ${JSON.stringify(repository)},
  AUTHOR: ${JSON.stringify(author)},
  VERSION: ${JSON.stringify(version)},
  VERSION_DATE: ${JSON.stringify(dateOnly)},
  VERSION_DATE_ISO: ${JSON.stringify(dateIso)},
});

export const LONG_VERSION_DATE = ${JSON.stringify(`${version} (${dateOnly})`)};
`;
};

const main = (): void => {
  logger.info('[main] Version generator script');

  try {
    const packageMetadata = readPackageJson();
    // APP_VERSION is set by CI (semantic-release output); falls back to package.json for local dev
    const version = process.env['APP_VERSION'] ?? packageMetadata.version;

    logger.info(`[main] Using version: ${version}`);

    const data = generateConstantsFile(packageMetadata, version);
    logger.info(`[main] Writing file "${versionGenFilename}"...`);
    writeFileSync(versionGenFilename, data, { encoding: 'utf8' });
    logger.info(`[main] File "${versionGenFilename}" written successfully.`);
  } catch (rawError: unknown) {
    const error = toError(rawError);
    const message = getErrorMessage(error);
    logger.error(`[main] Error: ${message}`, { error });
    process.exit(1);
  }
};

main();
