// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.ts
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: "personal-telegram-assist",
  DESCRIPTION: "A personal Telegram AI assistant powered by Claude Agent SDK",
  REPOSITORY: "https://github.com/amwebexpert/personal-telegram-assistant",
  AUTHOR: "amwebexpert@gmail.com",
  VERSION: "1.3.0",
  VERSION_DATE: "2026-05-21",
  VERSION_DATE_ISO: "2026-05-21T11:03:35.152Z",
});

export const LONG_VERSION_DATE = "1.3.0 (2026-05-21)";
